# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe11ee8eb5d924d02d9d083fbfd1f90525c942d277f5aa643288de67b68e5e589b3ea24158d274e31bddc56f7d13023d4e3f24ce07f2102e82ae56654681c1f5

test:
  secret_key_base: 2ce1da0c0940fb002c952ba20a8c24dfa77443beb219cf9b089a296bf41479f01bf640c403dfea222d41ffb9b9ff3f31aaa4e648eb5c1787133613feeb6926c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
